<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Prerana" name="Command line test" tests="3" failures="1" timestamp="10 Jun 2014 06:48:54 GMT" time="3.59" errors="0">
  <testcase name="getGamesAgainstAI" time="0.256" classname="ttt.model.dao.UserDaoTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at ttt.model.dao.UserDaoTest.getGamesAgainstAI(UserDaoTest.java:23)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:155)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- getGamesAgainstAI -->
  <testcase name="getPlayer" time="0.002" classname="ttt.model.dao.UserDaoTest"/>
  <testcase name="getSavedGames" time="0.007" classname="ttt.model.dao.UserDaoTest"/>
</testsuite> <!-- Command line test -->
